# Generated by Django 3.1.5 on 2021-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sells',
            field=models.BooleanField(default=False),
        ),
    ]
